SELECT * 
FROM public."Decode_Labs";

-- Total Quantity sold
SELECT 
	SUM("Quantity") AS total_quantity
FROM public."Decode_Labs";

-- Total Number of orders
SELECT 
	COUNT("OrderID") AS total_orders
FROM public."Decode_Labs";

-- Average Order Value
WITH average_order_calc AS(
	SELECT
		SUM("TotalPrice") AS total_amount,
		COUNT("OrderID") AS total_orders
	FROM public."Decode_Labs"
)
SELECT
	ROUND(
		(total_amount / total_orders),0) AS average_order_value
FROM average_order_calc;

-- Most sold product
SELECT 
	"Product",
	COUNT("Product") AS frequency
FROM public."Decode_Labs"
GROUP BY "Product" 
ORDER BY frequency DESC;

-- Quantity sales and total amount  by Product
SELECT
	"Product",
	SUM("Quantity") AS total_quantity,
	SUM("TotalPrice") AS total_amount
FROM public."Decode_Labs"
GROUP BY "Product" 
ORDER BY total_amount DESC;

-- Total amount generated by referral source / Customer Acq channel
SELECT
	"ReferralSource",
	SUM("TotalPrice") AS total_amount
FROM public."Decode_Labs"
GROUP BY "ReferralSource"
ORDER BY total_amount DESC;

-- Payment method usage frequency
SELECT
	"PaymentMethod",
	COUNT("PaymentMethod") AS payment_method_usage
FROM public."Decode_Labs"
GROUP BY "PaymentMethod"
ORDER BY payment_method_usage DESC;

-- Most Effective Referral Source. customer acqusi channel
SELECT 
	"ReferralSource",
	COUNT("ReferralSource") AS frequency
FROM public."Decode_Labs"
GROUP BY "ReferralSource"
ORDER BY frequency DESC;

-- TOP 10 StreetS with the most order delivery
SELECT
	"ShippingAddress",
	COUNT("OrderID") AS total_orders_delivered
FROM public."Decode_Labs"
GROUP BY "ShippingAddress"
ORDER BY total_orders_delivered DESC
LIMIT 10;

-- Yearly revenue
SELECT
	EXTRACT(YEAR FROM "Date") AS year_,
	SUM("TotalPrice") AS total_amount
FROM public."Decode_Labs"
GROUP BY year_
ORDER BY year_ ASC;

-- Monthly and yearly revenue trend
SELECT
	EXTRACT(YEAR FROM "Date") AS year_,
	EXTRACT(MONTH FROM "Date") AS month_,
	SUM("TotalPrice") AS total_amount
FROM public."Decode_Labs"
GROUP BY year_,month_
ORDER BY year_,month_ ASC;

-- Yearly Growth rate
WITH yearly_revenue AS(
	SELECT
		EXTRACT(YEAR FROM "Date") AS year_,
		SUM("TotalPrice") AS total_amount
	FROM public."Decode_Labs"
	GROUP BY year_
	ORDER BY year_ ASC
),
Preceding_rev_calc AS(
	SELECT
		year_,
		total_amount,
		LAG(total_amount) OVER(ORDER BY year_) AS prev_revenue
	FROM yearly_revenue
)
SELECT
	year_,
	total_amount,
	ROUND(
		(total_amount - prev_revenue) * 100.0 / prev_revenue,2) revenue_growth_perc
FROM Preceding_rev_calc

-- Month_year growth
WITH year_month_revenue AS(
	SELECT
		EXTRACT(YEAR FROM "Date") AS year_,
		EXTRACT(MONTH FROM "Date") AS month_,
		SUM("TotalPrice") AS total_amount
	FROM public."Decode_Labs"
	GROUP BY year_, month_
	ORDER BY year_,month_ ASC
),
Preceding_rev_calc AS(
	SELECT
		year_,
		month_,
		total_amount,
		LAG(total_amount) OVER(ORDER BY year_, month_) AS prev_revenue
	FROM year_month_revenue
)
SELECT
	year_,
	month_,
	total_amount,
	ROUND(
		(total_amount - prev_revenue) * 100.0 / prev_revenue,2) revenue_growth_perc
FROM Preceding_rev_calc
GROUP BY year_, month_, total_amount, prev_revenue
ORDER BY year_, month_;



-- Products that dominated each year in terms of revenue
SELECT
	EXTRACT(YEAR FROM "Date") AS year_,
	("Product") AS product,
	SUM("TotalPrice") AS total_amount
FROM public."Decode_Labs"
GROUP BY year_, product
ORDER BY year_ ASC, total_amount DESC;

-- Coupon effect on Revenue
SELECT
	"CouponCode",
	SUM("TotalPrice")
FROM public."Decode_Labs"
GROUP BY "CouponCode"

--- Order status analytics
SELECT
	"OrderStatus",
	COUNT("OrderStatus") AS count_of_order_status
FROM public."Decode_Labs"
GROUP BY "OrderStatus"
ORDER BY count_of_order_status DESC;

-- Order Cancelling Rate
WITH cancelled_calc AS (
	SELECT
		COUNT("OrderStatus") AS cancelled_order_status
	FROM public."Decode_Labs"
	WHERE "OrderStatus" = 'Cancelled'
)
SELECT
	ROUND(
	c.cancelled_order_status * 100.0 / COUNT(o."OrderStatus"),2) AS Cancelling_rate
FROM public."Decode_Labs"o
CROSS JOIN cancelled_calc c
GROUP BY cancelled_order_status;

